version: 2
jobs:
  build:
    working_directory: .
    docker:
      - image: circleci/node:7.10.0
    steps:
      - deploy:
          name: Deploys
          command: |
            npm install && npm run deploy
           